"use client";

import { Component, Suspense, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Canvas, useFrame } from "@react-three/fiber";
import { Environment, Lightformer, Sparkles, useGLTF } from "@react-three/drei";
import * as THREE from "three";

/**
 * Intro loader: a real 3D roasted bean (public/models/coffee-bean.glb,
 * generated by tools/blender/coffee_bean.py) arrives as two halves that
 * lock together along the crease, turns in the light, then shrinks up to
 * make room for the tagline.
 */

const MODEL = "/models/coffee-bean.glb";
useGLTF.preload(MODEL);

// Timeline in seconds, measured from the moment the model is on screen.
const T = {
  flyEnd: 2.2, // halves arrive, still slightly apart
  join: 2.6, // halves lock together
  shrink: 3.9, // bean shrinks up, tagline appears
  fade: 5.4, // overlay fades out
  done: 6.3, // hand over to the hero
};

type Phase = "loading" | "assemble" | "whole" | "text" | "fade";

const clamp01 = (x: number) => Math.min(1, Math.max(0, x));
const lerp = (a: number, b: number, t: number) => a + (b - a) * t;
const easeOutExpo = (t: number) => (t >= 1 ? 1 : 1 - Math.pow(2, -10 * t));
const easeInCubic = (t: number) => t * t * t;
const easeInOutCubic = (t: number) => (t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2);
const easeInOutSine = (t: number) => -(Math.cos(Math.PI * t) - 1) / 2;

function Bean({ onReady }: { onReady: () => void }) {
  const { scene } = useGLTF(MODEL);
  const whole = useRef<THREE.Group>(null);
  const sweep = useRef<THREE.PointLight>(null);
  const start = useRef<number | null>(null);

  const [left, right] = useMemo(() => {
    scene.traverse((o) => {
      const mesh = o as THREE.Mesh;
      if (!mesh.isMesh) return;
      const mat = mesh.material as THREE.MeshPhysicalMaterial;
      mat.envMapIntensity = 1.1;
    });
    return [scene.getObjectByName("BeanLeft")!, scene.getObjectByName("BeanRight")!];
  }, [scene]);

  useEffect(() => {
    onReady();
  }, [onReady]);

  useFrame((state) => {
    if (start.current === null) start.current = state.clock.elapsedTime;
    const t = state.clock.elapsedTime - start.current;

    // Halves fly in from opposite sides, tumbling, and stop just apart.
    const f = easeOutExpo(clamp01(t / T.flyEnd));
    const gap = lerp(0.14, 0, easeInCubic(clamp01((t - T.flyEnd) / (T.join - T.flyEnd))));
    left.position.set(lerp(-3.6, -gap, f), lerp(1.0, 0, f), lerp(-2, 0, f));
    left.rotation.set(lerp(1.4, 0, f), lerp(-2.6, 0, f), lerp(-0.9, 0, f));
    right.position.set(lerp(3.6, gap, f), lerp(-1.0, 0, f), lerp(-2, 0, f));
    right.rotation.set(lerp(-1.4, 0, f), lerp(2.6, 0, f), lerp(0.9, 0, f));

    // Damped "click" when the halves lock.
    const k = t - T.join;
    const pulse = k > 0 ? Math.exp(-k * 8) * Math.sin(k * 28) * 0.04 : 0;

    // Shrink and rise to make room for the tagline.
    const s = easeInOutCubic(clamp01((t - T.shrink) / 1.1));

    const g = whole.current!;
    // Keep the bean to roughly half the screen width on tall/narrow screens.
    const visibleWidth = 2 * 4.4 * Math.tan(THREE.MathUtils.degToRad(15)) * (state.size.width / state.size.height);
    const fit = Math.min(1, (visibleWidth * 0.5) / 0.72);
    g.scale.setScalar(fit * lerp(1, 0.46, s) * (1 + pulse));
    g.position.y = lerp(0, 0.66, s) + Math.sin(t * 1.3) * 0.015;
    g.rotation.y = lerp(-0.5, 0.45, easeInOutSine(clamp01(t / 5.5)));
    g.rotation.x = -0.12 + Math.sin(t * 0.8) * 0.04;

    // Slow camera push-in and a highlight sliding across the oily roast.
    state.camera.position.z = lerp(4.4, 3.9, easeInOutSine(clamp01(t / 5)));
    if (sweep.current) {
      sweep.current.position.x = lerp(-2.2, 2.2, easeInOutSine(clamp01((t - 1.2) / 3.8)));
      sweep.current.intensity = 6 * Math.sin(Math.PI * clamp01((t - 1.2) / 3.8));
    }
  });

  return (
    <>
      <group ref={whole}>
        <primitive object={left} />
        <primitive object={right} />
      </group>
      <pointLight ref={sweep} position={[-2.2, 0.6, 1.6]} color="#ffd9a8" distance={6} decay={1.5} />
    </>
  );
}

function Lights() {
  return (
    <>
      <ambientLight intensity={0.08} />
      <directionalLight position={[-2.5, 2.5, 3]} intensity={1.6} color="#ffe6c7" />
      {/* warm rim from behind so the silhouette glows against the dark */}
      <spotLight position={[2.5, 1.5, -3]} angle={0.6} penumbra={1} intensity={60} color="#ff9b45" />
      <spotLight position={[-2.5, -1.5, -2.5]} angle={0.6} penumbra={1} intensity={25} color="#b8742f" />
      <Environment resolution={256} frames={1}>
        <Lightformer form="rect" intensity={2.2} color="#fff1dc" position={[-3, 2, 3]} scale={[3, 2, 1]} />
        <Lightformer form="rect" intensity={1.4} color="#ffb870" position={[3, 0.5, -1]} scale={[1.5, 4, 1]} />
        <Lightformer form="circle" intensity={0.8} color="#ffffff" position={[0, 4, 1]} scale={2} />
      </Environment>
    </>
  );
}

/** Skips the intro if WebGL is unavailable or the model fails to load. */
class SceneBoundary extends Component<{ onError: () => void; children: ReactNode }, { failed: boolean }> {
  state = { failed: false };
  static getDerivedStateFromError() {
    return { failed: true };
  }
  componentDidCatch() {
    this.props.onError();
  }
  render() {
    return this.state.failed ? null : this.props.children;
  }
}

export default function Hero3DScene({ onIntroComplete }: { onIntroComplete: () => void }) {
  const [phase, setPhase] = useState<Phase>("loading");
  const [joined, setJoined] = useState(false);

  // Don't hold visitors hostage if the model is slow to arrive.
  useEffect(() => {
    if (phase !== "loading") return;
    const bail = setTimeout(onIntroComplete, 8000);
    return () => clearTimeout(bail);
  }, [phase, onIntroComplete]);

  const [started, setStarted] = useState(false);

  useEffect(() => {
    if (!started) return;
    const ms = (s: number) => s * 1000;
    const timers = [
      setTimeout(() => setJoined(true), ms(T.join)),
      setTimeout(() => setPhase("whole"), ms(T.join + 0.2)),
      setTimeout(() => setPhase("text"), ms(T.shrink + 0.3)),
      setTimeout(() => setPhase("fade"), ms(T.fade)),
      setTimeout(onIntroComplete, ms(T.done)),
    ];
    return () => timers.forEach(clearTimeout);
  }, [started, onIntroComplete]);

  const handleReady = useMemo(
    () => () => {
      setStarted(true);
      setPhase((p) => (p === "loading" ? "assemble" : p));
    },
    [],
  );

  return (
    <AnimatePresence>
      {phase !== "fade" && (
        <motion.div
          initial={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.9 }}
          className="absolute inset-0 z-[120] overflow-hidden"
          style={{
            background: "radial-gradient(circle at center, rgba(28,16,8,0.96), rgba(5,5,5,1))",
          }}
        >
          {/* ambient glow */}
          <motion.div
            animate={{ scale: [1, 1.15, 1], opacity: [0.25, 0.45, 0.25] }}
            transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
            className="absolute left-1/2 top-1/2 w-[800px] h-[800px] -translate-x-1/2 -translate-y-1/2 rounded-full blur-3xl"
            style={{ background: "radial-gradient(circle, rgba(180,130,70,0.18), transparent 70%)" }}
          />

          {/* flash when the halves lock */}
          <AnimatePresence>
            {joined && phase !== "text" && (
              <motion.div
                initial={{ opacity: 0.7, scale: 0.3 }}
                animate={{ opacity: 0, scale: 1.6 }}
                transition={{ duration: 1.1, ease: [0.16, 1, 0.3, 1] }}
                className="absolute left-1/2 top-1/2 w-[520px] h-[520px] -translate-x-1/2 -translate-y-1/2 rounded-full pointer-events-none"
                style={{ background: "radial-gradient(circle, rgba(255,190,120,0.35), transparent 65%)" }}
              />
            )}
          </AnimatePresence>

          <SceneBoundary onError={onIntroComplete}>
            <Canvas
              className="!absolute inset-0"
              dpr={[1, 2]}
              gl={{ antialias: true, alpha: true }}
              camera={{ position: [0, 0, 4.4], fov: 30 }}
            >
              <Lights />
              <Sparkles count={70} scale={[6, 4, 2]} size={2.2} speed={0.25} opacity={0.55} color="#d9a066" />
              <Suspense fallback={null}>
                <Bean onReady={handleReady} />
              </Suspense>
            </Canvas>
          </SceneBoundary>

          {phase === "loading" && (
            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: [0.2, 0.6, 0.2] }}
              transition={{ duration: 1.8, repeat: Infinity, delay: 0.6 }}
              className="absolute bottom-16 w-full text-center text-[11px] uppercase tracking-[0.4em] text-[#b48246]"
            >
              Roasting
            </motion.p>
          )}

          {phase === "text" && (
            <motion.h1
              initial={{ opacity: 0, y: 80, filter: "blur(14px)" }}
              animate={{ opacity: 1, y: 0, filter: "blur(0px)" }}
              transition={{ duration: 1.2, ease: [0.16, 1, 0.3, 1] }}
              className="absolute inset-x-0 top-1/2 -translate-y-1/2 z-30 text-white text-center px-6 pointer-events-none"
              style={{
                fontSize: "clamp(2rem, 5vw, 5rem)",
                fontFamily: "serif",
                textShadow: "0 0 40px rgba(180,130,70,0.25)",
              }}
            >
              From the Hills to Your Cup
            </motion.h1>
          )}
        </motion.div>
      )}
    </AnimatePresence>
  );
}
